<?php
/**
 * Cart inquiry 
 *
 * @category   Ranosys
 * @package    Ranosys_Inquiry
 * @author     Ranosys Technologies Pvt. Ltd. 
 */  
?>
<?php
$enableorDisable = Mage::getStoreConfig('ranosys/ranosys_group/ranosys_enabledisable',Mage::app()->getStore());

if($enableorDisable==1){      
    $cart_qty = (int) Mage::getModel('checkout/cart')->getQuote()->getItemsQty();
    if($cart_qty) 
    {
        $itemsCollection = Mage::getSingleton('checkout/session')->getQuote()->getItemsCollection();
        $itemsVisible = Mage::getSingleton('checkout/session')->getQuote()->getAllVisibleItems();
        $items = Mage::getSingleton('checkout/session')->getQuote()->getAllItems();
 
        foreach($items as $item) {
            $product['id'][]=$item->getProductId();
            $product['name'][]=$item->getName();
            $product['sku'][]=$item->getSku();
            }
            $productId=implode(',',$product['id']);
            $productName=implode(',',$product['name']);
            $productSku=implode(',',$product['sku']);
?>
<div id="messages"><?php //echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="page-title">
    <?php 
    $cartTittle = Mage::getStoreConfig('ranosys/ranosys_group/ranosys_input',Mage::app()->getStore());
    if($cartTittle!=''){
        $tittle=$cartTittle;
    }
    else{
        $tittle=Mage::helper('inquiry')->__('Cart Inquiry');
    }?>
    <h1><?php echo $tittle ?></h1>
</div>
<form action="<?php echo $this->getUrl('inquiry/index/save') ?>" id="inquiryForm" method="post" class="scaffold-form">
    <div class="fieldset">
        <p class="required"><?php echo Mage::helper('inquiry')->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="firstname" class="required"><em>*</em><?php echo Mage::helper('inquiry')->__('First Name') ?></label>
                    <div class="input-box">
                        <input name="firstname" id="firstname" title="<?php echo Mage::helper('inquiry')->__('First Name') ?>" value="" class="input-text required-entry validate-alpha" type="text" />
                    </div>
                </div>
                 <div class="field">
                    <label for="lastname" class="required"><em>*</em><?php echo Mage::helper('inquiry')->__('Last Name') ?></label>
                    <div class="input-box">
                        <input name="lastname" id="lastname" title="<?php echo Mage::helper('inquiry')->__('Last Name') ?>" value="" class="input-text required-entry validate-alpha" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('inquiry')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('inquiry')->__('Email') ?>" value="" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
                    </div>
                </div>
            </li>
            <li>
                <label for="phone"><?php echo Mage::helper('inquiry')->__('Phone') ?></label>
                <div class="input-box">
                    <input name="phone" id="phone" title="<?php echo Mage::helper('inquiry')->__('Phone') ?>" value="" class="input-text" type="text" />
                </div>
            </li>
            <li class="wide">
                <label for="message" class="required"><em>*</em><?php echo Mage::helper('inquiry')->__('Message') ?></label>
                <div class="input-box">
                    <textarea name="message" id="message" title="<?php echo Mage::helper('inquiry')->__('Message') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
        <input type="hidden" name="productId" value="<?php echo $productId; ?>">
        <input type="hidden" name="productName" value="<?php echo $productName;?>">
        <input type="hidden" name="productSku" value="<?php echo $productSku;?>">
    <div class="buttons-set">
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('inquiry')->__('Submit') ?>" class="button" style="float: left !important;"><span><span><?php echo Mage::helper('inquiry')->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('inquiryForm', true);
//]]>
</script>
<?php  } 
   
}?>
